# docker-compose.yml

version: '3.8'
services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydatabase
      - JWT_SECRET=your-super-secret-key-here
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && npm run start:prod"
    volumes:
      - ./.env:/usr/src/app/.env

  postgres:
    image: postgres:13.5
    restart: unless-stopped
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - nest-postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  nest-postgres-data:
    name: nest-postgres-data


